version: '3.9'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: esp_data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password